baseURL = "https://okfn.de"
languageCode = "de-DE"
title = "OKF"
defaultContentLanguage = "de"
enableRobotsTXT = true

[params]
  twitter = "okfde"
  twitter_site_id = "255123777" 
  author = "okfde" 
  keywords = ["Offene Daten", "Civic Tech", "Open Government", "Offene Bildung", "Digitale Mündigkeit" , "Informationsfreiheit", " Open Data"]
  subtitle = "Open Knowledge Foundation Deutschland e.V."

[permalinks]
  blog = 'blog/:year/:month/:slug/'
  tags = 'tags/:slug/'
  authors = 'authors/:slug/'

[taxonomies]
  tags = 'tags'
  authors = 'authors'

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = 'authors'
weight =  80
  [[related.indices]]
    name = 'date'
    weight = 40
    pattern = 2006
  [[related.indices]]
    name = 'tags'
    weight = 60

[mediaTypes]        
  [mediaTypes."application/atom"]
    suffixes = ["xml"]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "atom"
    isPlainText = false
  [outputFormats.Rss]
    mediaType = "application/rss+xml"
    basename = "rss"
    isPlainText = false
  [outputFormats.Json]
    mediaType = "application/json"
    baseName = "index"

[languages]
  [languages.de]
    title = "OKF"
    languageName = "DE" 
    weight = 1
  [languages.en]
    title = "OKF DE"
    languageName = "EN"
    weight = 2
    
  
[outputs]
home = ["HTML", "Json"]
section = [ "HTML", "Atom", "Json", "Rss" ]

[frontmatter]
date  = [":filename", ":default"]

[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      precision = 0
    [minify.tdewolff.json]
      precision = 0
    [minify.tdewolff.svg]
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false